In [1]:
name="Calvin"
hourly_wage=63.38
hours=8
weekly_pay=(hourly_wage*hours*5)
print(f"{name} earns {weekly_pay} per week")

Calvin earns 2535.2000000000003 per week

In [2]:
temps=[61,65,72,58,70,74,68]
high=0
for s in temps:
    if s >65:
        high=high+1
print(high)

4

In [3]:
def to_celsius(f):
    return (f-32)*5/9
print(round(to_celsius(temps[0]),1))

16.1

In [4]:
movie ={"title":"Die Hard","year":1965,"rating":"R"}
for key, value in movie.items():
    print(key,":",value)

title : Die Hard
year : 1965
rating : R

In [5]:
import pandas as pd
df=pd.read_csv("Downloads/chickwts.csv")
df.head()
df.shape
df.describe()

       Unnamed: 0      weight
count   71.000000   71.000000
mean    36.000000  261.309859
std     20.639767   78.073700
min      1.000000  108.000000
25%     18.500000  204.500000
50%     36.000000  258.000000
75%     53.500000  323.500000
max     71.000000  423.000000

In [6]:
import pandas as pd
df=pd.read_csv("Downloads/chickwts.csv")
df.head()

   Unnamed: 0  weight       feed
0           1     179  horsebean
1           2     160  horsebean
2           3     136  horsebean
3           4     227  horsebean
4           5     217  horsebean

In [7]:
import pandas as pd
#df=pd.read_csv("Downloads/chickwts.csv") will output 71,3
df = pd.read_csv("Downloads/chickwts.csv", index_col=0)
df.shape

(71, 2)

In [8]:
import pandas as pd
df=pd.read_csv("Downloads/chickwts.csv")
df.describe()

       Unnamed: 0      weight
count   71.000000   71.000000
mean    36.000000  261.309859
std     20.639767   78.073700
min      1.000000  108.000000
25%     18.500000  204.500000
50%     36.000000  258.000000
75%     53.500000  323.500000
max     71.000000  423.000000

In [9]:
#The describe() output appears to run a statistical analysis of the list showing min,max,average, and standard deviations.  Only think to surprise me is how big the chickens are unless they are like a group of chickens.Module 2 Lab 1: Python Warm-Up + First Push